### PR TITLE
feat(no-method-signature): properly handle `Readonly<{TSMethodSignature}>`

### PR DESCRIPTION
**Pull request by rafaelss95**
Fixes: #261.

### CODE REVIEW

**Comment by rafaelss95** [comment]
@RebeccaStevens I noticed that you suggested a new option for this rule in #261... so I'm opening it here as a draft to check if it's really necessary and if so, how can I build the selector based on option inside `createRule`?

**Comment by RebeccaStevens** [comment]
Instead of modifying the selector, inside the `checkTSMethodSignature` you could walk up the AST to see if the node is shallowly inside a `Readonly`.

[There are already some util methods that exist for walking the AST.](https://github.com/jonaskello/eslint-plugin-functional/blob/master/src/util/tree.ts)

I'll give this PR a proper review tomorrow.

**Comment by rafaelss95** [comment]
Thanks for the fast feedback, really appreciate that!

Hmm... walking without using selectors will require a bit more work then. I'll try to take a look at it tomorrow 😄

**Comment by rafaelss95** [comment]
@RebeccaStevens I've just changed the implementation to use explicit conditionals instead of selectors, as you mentioned. Do you still think it's valuable to have an option for this?

**Pull request merged**
