### PR TITLE
Automerge dependabot updates

### PR DESCRIPTION
**Pull request by RebeccaStevens**

### CODE REVIEW

**Review by jonaskello — APPROVED** [review]

**Comment by jonaskello** [comment]
Automerge seems like a good idea, have not tried it before so this will be interesting :-).

**Comment by RebeccaStevens** [comment]
I'll keep an eye on it to make sure it doesn't break anything.

**Comment by RebeccaStevens** [comment]
@jonaskello Would you be able to setup a `GITHUB_TOKEN` secret for this to work?

https://github.com/jonaskello/eslint-plugin-functional/settings/secrets/actions

**Comment by jonaskello** [comment]
@RebeccaStevens I have not used the token before but it seems it is something automatic according to the docs here:

https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret

> GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow. You can use the GITHUB_TOKEN to authenticate in a workflow run.

I guess we will know once this workflow triggers :-)

**Comment by RebeccaStevens** [comment]
It being automatically makes things easy then 🙂.

The job has triggered a few times already but failed due to an upstream issue in one of the actions. I've submitted a fix that was just merged in a few minutes ago. Hopefully they'll be a new release soon.

**Pull request merged**
